@local=http://localhost:4000
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2Nzg4ZjNjNGI5ZDU1ZTMwMmYzMDYyMWEiLCJiaXoiOnRydWUsImlhdCI6MTczNzQ3MDY5NX0.8rsjG6y3AA-gU0siojzM7ECt_tRwXWhQMdu54w-OdeA
@adminToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2Nzc5MWM3NjY2NDc3OGQzMjFjZDM3ZTciLCJiaXoiOnRydWUsImlhdCI6MTczNTk5MDQzOX0.ybGlsw6CNfwIlm8aZHxMXmWFb7heHfV_q-mEqCOP9YU

POST {{local}}/api/users/
Content-Type: application/json

{"name":{"first":"tom","middle":"","last":"dekel"},
"phone":"1231231233",
"address":{"state":"asdasd","country":"asd","city":"asd","street":"sasd","houseNumber":"asd","zip":"asd"},
"image":{"url":"asdasd","alt":"asdads"},
"email":"tom20@gmail.com",
"password":"Aa123456",
"biz":"true"}

###
POST {{local}}/api/auth/
Content-Type: application/json

{
    "email": "admin@admin.com",
    "password":"Aa123456"
    }

###
GET {{local}}/api/users/6774485859c9fe8b178d8ff6
x-auth-token: {{adminToken}}
###
GET {{local}}/api/users/
x-auth-token:{{adminToken}}

###
PUT {{local}}/api/users/67791bba664778d321cd37e4
x-auth-token: {{token}}
Content-Type: application/json

{
    "name":{"first":"tommmmm","middle":"","last":"dekel"},
"phone":"322222ss33",
"address":{"state":"asdasd","country":"asd","city":"asd","street":"sasd","houseNumber":"asd","zip":"asd"},
"image":{"url":"asdasd","alt":"asdads"}
}

###
PATCH {{local}}/api/users/676e63279dee467bd140d642
x-auth-token: {{token}}
Content-Type: application/json

###
DELETE {{local}}/api/users/6788f3cdb9d55e302f30621e
x-auth-token: {{adminToken}}

###
POST {{local}}/api/cards/
x-auth-token: {{token}}
Content-Type: application/json

{
    "title":"hahaha",
"subtitle":"hahaha",
"description":"haha",
"phone":"052333333",
"email":"tom210@gmail.com",
"web":"www.store.co.il",
"image":{
    "url":"www.gg.com",
    "alt":"www.gg.com"
},
"address":{
"state":"someplace",
"country":"someplace",
"city":"someplace",
"street":"someplace",
"houseNumber":"someplace",
"zip":"someplace"
}
}

###
GET {{local}}/api/cards/

###
GET {{local}}/api/cards/678f939faff2c772dfdc66b3

###
GET {{local}}/api/cards/my-cards
x-auth-token: {{token}}

###
PUT {{local}}/api/cards/678fa0fdff87c76f8fd67fe1
x-auth-token: {{token}}
Content-Type: application/json

{
    "title":"h234asdasdas23ha",
"subtitle":"hahaha",
"description":"haha",
"phone":"052333333",
"web":"www.store.co.il",
"image":{
    "url":"www.gg.com",
    "alt":"www.gg.com"
},
"address":{
"state":"someplace",
"country":"someplace",
"city":"someplace",
"street":"someplace",
"houseNumber":"someplace",
"zip":"1313"
}
}

###
PATCH {{local}}/api/cards/678fa0fdff87c76f8fd67fe1
x-auth-token: {{adminToken}}

###
DELETE {{local}}/api/cards/678fa0fdff87c76f8fd67fe1
x-auth-token:{{adminToken}}

###
PATCH {{local}}/api/cards/biznumberchange/678f939faff2c772dfdc66b3
x-auth-token:{{token}}
Content-Type: application/json

{
"newBizNumber":"111111111"
}
